name: go-learn

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  precommit:
    name: Lint general files
    runs-on: ubuntu-latest
    env:
      SKIP: golangci-lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --show-diff-on-failure --color=always

  golangci:
    name: Lint Go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Test
        run: go test -cover ./...
